### ISSUE TITLE
Header height is wrong

### ISSUE THREAD

**Issue by dnevozhai1** [Cu7ious/Promin-App#24]
On phones with a display notch, the logo appears to be under the notch. This looks bad.

When I measure the blue area height in a browser, it's 70 pt. While in the design it's 88.

**Comment by garys-primary** [comment]
@Cu7ious I think you fixed this already?

**Comment by Cu7ious** [comment]
Need to double check on this, and I'll be able to do it tonight

**Comment by Cu7ious** [comment]
Done
